name: Sync LeetCode Submissions

on:
  workflow_dispatch:
  schedule:
    # Runs daily at midnight UTC
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  sync:
    name: Sync LeetCode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync LeetCode Solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions
          verbose: true
